services:
  reco_schedular_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reco_schedular_worker
    command: celery -A celeryapp.app worker --loglevel=info
    network_mode: "host"
  reco_schedular_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reco_schedular_beat
    command: celery -A celeryapp.app beat --loglevel=info
    network_mode: "host"
  flower:
    image: mher/flower:master
    container_name: flower
    environment:
      - CELERY_BROKER_URL=redis://default:i2am2b9329LmHlvxLVTaA@localhost:6379/0
    network_mode: "host"